const _ = require('lodash');
let cards = [
  {
    id: '61177648539dd0520f4066d8',
    address: null,
    badges: {
      attachmentsByType: { trello: { board: 0, card: 0 } },
      location: false,
      votes: 0,
      viewingMemberVoted: false,
      subscribed: false,
      fogbugz: '',
      checkItems: 0,
      checkItemsChecked: 0,
      checkItemsEarliestDue: null,
      comments: 0,
      attachments: 0,
      description: false,
      due: null,
      dueComplete: false,
      start: null,
    },
    checkItemStates: null,
    closed: false,
    coordinates: null,
    creationMethod: null,
    dueComplete: false,
    dateLastActivity: '2021-08-14T07:52:40.565Z',
    desc: '',
    descData: null,
    due: null,
    dueReminder: null,
    email: 'steve97883180+2o50qsfnmbgrr42xsio+2wvk6y1a7tzxigfzljs+10tma2pwab@boards.trello.com',
    idBoard: '609f488638122f7a82bf31b4',
    idChecklists: [],
    idLabels: [],
    idList: '609f490472813c8656dc47fb',
    idMembers: [],
    idMembersVoted: [],
    idShort: 44,
    idAttachmentCover: null,
    labels: [],
    limits: {
      attachments: { perCard: { status: 'ok', disableAt: 1000, warnAt: 800 } },
      checklists: { perCard: { status: 'ok', disableAt: 500, warnAt: 400 } },
      stickers: { perCard: { status: 'ok', disableAt: 70, warnAt: 56 } },
    },
    locationName: null,
    manualCoverAttachment: false,
    name: 'Restful API',
    pos: 4095.9375,
    shortLink: 'CaWZy9Ee',
    shortUrl: 'https://trello.com/c/CaWZy9Ee',
    staticMapUrl: null,
    start: null,
    subscribed: false,
    url: 'https://trello.com/c/CaWZy9Ee/44-restful-api',
    cover: {
      idAttachment: null,
      color: null,
      idUploadedBackground: null,
      size: 'normal',
      brightness: 'dark',
      idPlugin: null,
    },
    isTemplate: false,
    cardRole: null,
    attachments: [],
    pluginData: [],
    customFieldItems: [],
  },
  {
    id: '61177648539dd0520f4066d9',
    address: null,
    badges: {
      attachmentsByType: { trello: { board: 0, card: 0 } },
      location: false,
      votes: 0,
      viewingMemberVoted: false,
      subscribed: false,
      fogbugz: '',
      checkItems: 0,
      checkItemsChecked: 0,
      checkItemsEarliestDue: null,
      comments: 0,
      attachments: 0,
      description: false,
      due: null,
      dueComplete: false,
      start: null,
    },
    checkItemStates: null,
    closed: false,
    coordinates: null,
    creationMethod: null,
    dueComplete: false,
    dateLastActivity: '2021-09-14T07:52:40.565Z',
    desc: '',
    descData: null,
    due: null,
    dueReminder: null,
    email: 'steve97883180+2o50qsfnmbgrr42xsio+2wvk6y1a7tzxigfzljs+10tma2pwab@boards.trello.com',
    idBoard: '609f488638122f7a82bf31b4',
    idChecklists: [],
    idLabels: [],
    idList: '609f490472813c8656dc47fb',
    idMembers: [],
    idMembersVoted: [],
    idShort: 44,
    idAttachmentCover: null,
    labels: [],
    limits: {
      attachments: { perCard: { status: 'ok', disableAt: 1000, warnAt: 800 } },
      checklists: { perCard: { status: 'ok', disableAt: 500, warnAt: 400 } },
      stickers: { perCard: { status: 'ok', disableAt: 70, warnAt: 56 } },
    },
    locationName: null,
    manualCoverAttachment: false,
    name: 'Restful API',
    pos: 4095.9375,
    shortLink: 'CaWZy9Ee',
    shortUrl: 'https://trello.com/c/CaWZy9Ee',
    staticMapUrl: null,
    start: null,
    subscribed: false,
    url: 'https://trello.com/c/CaWZy9Ee/44-restful-api',
    cover: {
      idAttachment: null,
      color: null,
      idUploadedBackground: null,
      size: 'normal',
      brightness: 'dark',
      idPlugin: null,
    },
    isTemplate: false,
    cardRole: null,
    attachments: [],
    pluginData: [],
    customFieldItems: [],
  },
  {
    id: '61177648539dd0520f4066d6',
    address: null,
    badges: {
      attachmentsByType: { trello: { board: 0, card: 0 } },
      location: false,
      votes: 0,
      viewingMemberVoted: false,
      subscribed: false,
      fogbugz: '',
      checkItems: 0,
      checkItemsChecked: 0,
      checkItemsEarliestDue: null,
      comments: 0,
      attachments: 0,
      description: false,
      due: null,
      dueComplete: false,
      start: null,
    },
    checkItemStates: null,
    closed: false,
    coordinates: null,
    creationMethod: null,
    dueComplete: false,
    dateLastActivity: '2021-10-14T07:52:40.565Z',
    desc: '',
    descData: null,
    due: null,
    dueReminder: null,
    email: 'steve97883180+2o50qsfnmbgrr42xsio+2wvk6y1a7tzxigfzljs+10tma2pwab@boards.trello.com',
    idBoard: '609f488638122f7a82bf31b4',
    idChecklists: [],
    idLabels: [],
    idList: '609f490472813c8656dc47fb',
    idMembers: [],
    idMembersVoted: [],
    idShort: 44,
    idAttachmentCover: null,
    labels: [],
    limits: {
      attachments: { perCard: { status: 'ok', disableAt: 1000, warnAt: 800 } },
      checklists: { perCard: { status: 'ok', disableAt: 500, warnAt: 400 } },
      stickers: { perCard: { status: 'ok', disableAt: 70, warnAt: 56 } },
    },
    locationName: null,
    manualCoverAttachment: false,
    name: 'Restful API',
    pos: 4095.9375,
    shortLink: 'CaWZy9Ee',
    shortUrl: 'https://trello.com/c/CaWZy9Ee',
    staticMapUrl: null,
    start: null,
    subscribed: false,
    url: 'https://trello.com/c/CaWZy9Ee/44-restful-api',
    cover: {
      idAttachment: null,
      color: null,
      idUploadedBackground: null,
      size: 'normal',
      brightness: 'dark',
      idPlugin: null,
    },
    isTemplate: false,
    cardRole: null,
    attachments: [],
    pluginData: [],
    customFieldItems: [],
  },
];

let obj = _.groupBy(
  cards,
  ({ dateLastActivity }) => new Date(Date.parse(dateLastActivity)).getMonth() + 1
);
console.log(obj);
